# At the moment, the latest release doesn't contain the yaml.UnmarshalStrict
# and yaml.DisallowUnknownFields functions. This override vendors the latest
# commit on `master`.
[[override]]
  name = "github.com/ghodss/yaml"
  revision = "25d852aebe32c875e9c044af3eef9c7dc6bc777f"

# The Kubernetes repositories aren't designed for public use, so they don't
# release versions with semver. We therefore pin them all to the same
# Kubernetes release version.
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/kubectl"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.16.0"

# k8s.io/kubectl uses v1 of blackfriday.
[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/kelda-inc/docker-registry-client"

[[constraint]]
  branch = "master"
  name = "github.com/kelda-inc/fsnotify"

# Match version of Docker used by Kubernetes (18.09.4).
[[constraint]]
  name = "github.com/docker/docker"
  revision = "be7ac8be2ae072032a4005e8f232be3fc57e4127"
