apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-update
spec:
  template:
    metadata:
      labels:
        service: test-update
    spec:
      containers:
      - name: test-update
        image: gcr.io/magda-221800/test-update:stage
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 0
